[package]
name = "beanstalkd-rs"
version = "0.2.0"
edition = "2024"
description = "Minimal rust beanstalkd client"
readme = "README.md"
repository = "https://github.com/ArtemIsmagilov/beanstalkd-rs"
license = "MIT"
keywords = ["beanstalkd", "client", "queue", "async"]
categories = ["network-programming", "asynchronous"]

[dependencies]
thiserror = "2.0.18"
smol = { version = "2.0.2", optional = true }
tokio = { version = "1.52.3", optional = true }

[features]
default = ["smol-comp"]
smol-comp = ["dep:smol"]
tokio-comp = ["dep:tokio", "tokio/net", "tokio/io-util"]

[[example]]
name = "simple"
required-features = ["smol-comp"]
